/* tslint:disable */
/* eslint-disable */
/**
 * Moorsyl API
 * SMS, phone verification, and webhook APIs for Mauritania.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SmsGet200Response,
  SmsGetRequest,
  SmsSend200Response,
  SmsSendRequest,
} from '../models/index';
import {
    SmsGet200ResponseFromJSON,
    SmsGet200ResponseToJSON,
    SmsGetRequestFromJSON,
    SmsGetRequestToJSON,
    SmsSend200ResponseFromJSON,
    SmsSend200ResponseToJSON,
    SmsSendRequestFromJSON,
    SmsSendRequestToJSON,
} from '../models/index';

export interface SmsGetOperationRequest {
    smsGetRequest: SmsGetRequest;
}

export interface SmsSendOperationRequest {
    smsSendRequest: SmsSendRequest;
}

/**
 * 
 */
export class SMSApi extends runtime.BaseAPI {

    /**
     * Retrieve the current status and details of a previously sent SMS message by its ID.
     * Get SMS status
     */
    async smsGetRaw(requestParameters: SmsGetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SmsGet200Response>> {
        if (requestParameters['smsGetRequest'] == null) {
            throw new runtime.RequiredError(
                'smsGetRequest',
                'Required parameter "smsGetRequest" was null or undefined when calling smsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKey authentication
        }

        const response = await this.request({
            path: `/sms/get`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SmsGetRequestToJSON(requestParameters['smsGetRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SmsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve the current status and details of a previously sent SMS message by its ID.
     * Get SMS status
     */
    async smsGet(requestParameters: SmsGetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SmsGet200Response> {
        const response = await this.smsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Send a text message to a Mauritanian phone number. The message is queued immediately and delivered through Mauritania-optimized carrier routing.
     * Send an SMS
     */
    async smsSendRaw(requestParameters: SmsSendOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SmsSend200Response>> {
        if (requestParameters['smsSendRequest'] == null) {
            throw new runtime.RequiredError(
                'smsSendRequest',
                'Required parameter "smsSendRequest" was null or undefined when calling smsSend().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKey authentication
        }

        const response = await this.request({
            path: `/sms`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SmsSendRequestToJSON(requestParameters['smsSendRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SmsSend200ResponseFromJSON(jsonValue));
    }

    /**
     * Send a text message to a Mauritanian phone number. The message is queued immediately and delivered through Mauritania-optimized carrier routing.
     * Send an SMS
     */
    async smsSend(requestParameters: SmsSendOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SmsSend200Response> {
        const response = await this.smsSendRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
