/* tslint:disable */
/* eslint-disable */
/**
 * Moorsyl API
 * SMS, phone verification, and webhook APIs for Mauritania.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  VerifyCheck200Response,
  VerifyCheckRequest,
  VerifyGet200Response,
  VerifySend200Response,
  VerifySendRequest,
} from '../models/index';
import {
    VerifyCheck200ResponseFromJSON,
    VerifyCheck200ResponseToJSON,
    VerifyCheckRequestFromJSON,
    VerifyCheckRequestToJSON,
    VerifyGet200ResponseFromJSON,
    VerifyGet200ResponseToJSON,
    VerifySend200ResponseFromJSON,
    VerifySend200ResponseToJSON,
    VerifySendRequestFromJSON,
    VerifySendRequestToJSON,
} from '../models/index';

export interface VerifyCheckOperationRequest {
    verifyCheckRequest: VerifyCheckRequest;
}

export interface VerifyGetRequest {
    verifySend200Response: VerifySend200Response;
}

export interface VerifySendOperationRequest {
    verifySendRequest: VerifySendRequest;
}

/**
 * 
 */
export class VerifyApi extends runtime.BaseAPI {

    /**
     * Validate the one-time code entered by the user and return approved for a correct match, or denied when the code is incorrect, expired, or already used.
     * Check a verification code
     */
    async verifyCheckRaw(requestParameters: VerifyCheckOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VerifyCheck200Response>> {
        if (requestParameters['verifyCheckRequest'] == null) {
            throw new runtime.RequiredError(
                'verifyCheckRequest',
                'Required parameter "verifyCheckRequest" was null or undefined when calling verifyCheck().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKey authentication
        }

        const response = await this.request({
            path: `/verify/check`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyCheckRequestToJSON(requestParameters['verifyCheckRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VerifyCheck200ResponseFromJSON(jsonValue));
    }

    /**
     * Validate the one-time code entered by the user and return approved for a correct match, or denied when the code is incorrect, expired, or already used.
     * Check a verification code
     */
    async verifyCheck(requestParameters: VerifyCheckOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VerifyCheck200Response> {
        const response = await this.verifyCheckRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve the current status and details of a phone verification by its ID.
     * Get verification status
     */
    async verifyGetRaw(requestParameters: VerifyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VerifyGet200Response>> {
        if (requestParameters['verifySend200Response'] == null) {
            throw new runtime.RequiredError(
                'verifySend200Response',
                'Required parameter "verifySend200Response" was null or undefined when calling verifyGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKey authentication
        }

        const response = await this.request({
            path: `/verify/get`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifySend200ResponseToJSON(requestParameters['verifySend200Response']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VerifyGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve the current status and details of a phone verification by its ID.
     * Get verification status
     */
    async verifyGet(requestParameters: VerifyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VerifyGet200Response> {
        const response = await this.verifyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Send a one-time passcode via SMS to the specified Mauritanian phone number. Returns a verificationId to use with the check endpoint.
     * Send a verification code
     */
    async verifySendRaw(requestParameters: VerifySendOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VerifySend200Response>> {
        if (requestParameters['verifySendRequest'] == null) {
            throw new runtime.RequiredError(
                'verifySendRequest',
                'Required parameter "verifySendRequest" was null or undefined when calling verifySend().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKey authentication
        }

        const response = await this.request({
            path: `/verify/send`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifySendRequestToJSON(requestParameters['verifySendRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VerifySend200ResponseFromJSON(jsonValue));
    }

    /**
     * Send a one-time passcode via SMS to the specified Mauritanian phone number. Returns a verificationId to use with the check endpoint.
     * Send a verification code
     */
    async verifySend(requestParameters: VerifySendOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VerifySend200Response> {
        const response = await this.verifySendRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
