/* tslint:disable */
/* eslint-disable */
/**
 * Moorsyl API
 * SMS, phone verification, and webhook APIs for Mauritania.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SmsGet200Response
 */
export interface SmsGet200Response {
    /**
     * 
     * @type {string}
     * @memberof SmsGet200Response
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SmsGet200Response
     */
    to: string;
    /**
     * 
     * @type {string}
     * @memberof SmsGet200Response
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof SmsGet200Response
     */
    body: string;
    /**
     * 
     * @type {string}
     * @memberof SmsGet200Response
     */
    status: SmsGet200ResponseStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof SmsGet200Response
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SmsGet200Response
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const SmsGet200ResponseStatusEnum = {
    Pending: 'pending',
    Processing: 'processing',
    Sent: 'sent',
    Failed: 'failed'
} as const;
export type SmsGet200ResponseStatusEnum = typeof SmsGet200ResponseStatusEnum[keyof typeof SmsGet200ResponseStatusEnum];


/**
 * Check if a given object implements the SmsGet200Response interface.
 */
export function instanceOfSmsGet200Response(value: object): value is SmsGet200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function SmsGet200ResponseFromJSON(json: any): SmsGet200Response {
    return SmsGet200ResponseFromJSONTyped(json, false);
}

export function SmsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SmsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'to': json['to'],
        'from': json['from'],
        'body': json['body'],
        'status': json['status'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function SmsGet200ResponseToJSON(json: any): SmsGet200Response {
    return SmsGet200ResponseToJSONTyped(json, false);
}

export function SmsGet200ResponseToJSONTyped(value?: SmsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'to': value['to'],
        'from': value['from'],
        'body': value['body'],
        'status': value['status'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

