/* tslint:disable */
/* eslint-disable */
/**
 * Moorsyl API
 * SMS, phone verification, and webhook APIs for Mauritania.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SmsGetRequest
 */
export interface SmsGetRequest {
    /**
     * 
     * @type {string}
     * @memberof SmsGetRequest
     */
    messageId: string;
}

/**
 * Check if a given object implements the SmsGetRequest interface.
 */
export function instanceOfSmsGetRequest(value: object): value is SmsGetRequest {
    if (!('messageId' in value) || value['messageId'] === undefined) return false;
    return true;
}

export function SmsGetRequestFromJSON(json: any): SmsGetRequest {
    return SmsGetRequestFromJSONTyped(json, false);
}

export function SmsGetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SmsGetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'messageId': json['messageId'],
    };
}

export function SmsGetRequestToJSON(json: any): SmsGetRequest {
    return SmsGetRequestToJSONTyped(json, false);
}

export function SmsGetRequestToJSONTyped(value?: SmsGetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messageId': value['messageId'],
    };
}

