/* tslint:disable */
/* eslint-disable */
/**
 * Moorsyl API
 * SMS, phone verification, and webhook APIs for Mauritania.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SmsSend200Response
 */
export interface SmsSend200Response {
    /**
     * 
     * @type {any}
     * @memberof SmsSend200Response
     */
    accepted: any | null;
    /**
     * 
     * @type {string}
     * @memberof SmsSend200Response
     */
    messageId: string;
    /**
     * 
     * @type {string}
     * @memberof SmsSend200Response
     */
    idempotencyKey: string;
    /**
     * 
     * @type {string}
     * @memberof SmsSend200Response
     */
    organizationId: string;
}

/**
 * Check if a given object implements the SmsSend200Response interface.
 */
export function instanceOfSmsSend200Response(value: object): value is SmsSend200Response {
    if (!('accepted' in value) || value['accepted'] === undefined) return false;
    if (!('messageId' in value) || value['messageId'] === undefined) return false;
    if (!('idempotencyKey' in value) || value['idempotencyKey'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    return true;
}

export function SmsSend200ResponseFromJSON(json: any): SmsSend200Response {
    return SmsSend200ResponseFromJSONTyped(json, false);
}

export function SmsSend200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SmsSend200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'accepted': json['accepted'],
        'messageId': json['messageId'],
        'idempotencyKey': json['idempotencyKey'],
        'organizationId': json['organizationId'],
    };
}

export function SmsSend200ResponseToJSON(json: any): SmsSend200Response {
    return SmsSend200ResponseToJSONTyped(json, false);
}

export function SmsSend200ResponseToJSONTyped(value?: SmsSend200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accepted': value['accepted'],
        'messageId': value['messageId'],
        'idempotencyKey': value['idempotencyKey'],
        'organizationId': value['organizationId'],
    };
}

