/* tslint:disable */
/* eslint-disable */
/**
 * Moorsyl API
 * SMS, phone verification, and webhook APIs for Mauritania.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SmsSendRequest
 */
export interface SmsSendRequest {
    /**
     * 
     * @type {string}
     * @memberof SmsSendRequest
     */
    to: string;
    /**
     * 
     * @type {string}
     * @memberof SmsSendRequest
     */
    from?: string;
    /**
     * 
     * @type {string}
     * @memberof SmsSendRequest
     */
    body: string;
    /**
     * 
     * @type {string}
     * @memberof SmsSendRequest
     */
    idempotencyKey?: string;
}

/**
 * Check if a given object implements the SmsSendRequest interface.
 */
export function instanceOfSmsSendRequest(value: object): value is SmsSendRequest {
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    return true;
}

export function SmsSendRequestFromJSON(json: any): SmsSendRequest {
    return SmsSendRequestFromJSONTyped(json, false);
}

export function SmsSendRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SmsSendRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'],
        'from': json['from'] == null ? undefined : json['from'],
        'body': json['body'],
        'idempotencyKey': json['idempotencyKey'] == null ? undefined : json['idempotencyKey'],
    };
}

export function SmsSendRequestToJSON(json: any): SmsSendRequest {
    return SmsSendRequestToJSONTyped(json, false);
}

export function SmsSendRequestToJSONTyped(value?: SmsSendRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'from': value['from'],
        'body': value['body'],
        'idempotencyKey': value['idempotencyKey'],
    };
}

