/* tslint:disable */
/* eslint-disable */
/**
 * Moorsyl API
 * SMS, phone verification, and webhook APIs for Mauritania.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Present when the requested sender ID is still awaiting approval: the message was sent from the default MOORSYL sender instead.
 * @export
 * @interface SmsSend200ResponseNotice
 */
export interface SmsSend200ResponseNotice {
    /**
     * 
     * @type {any}
     * @memberof SmsSend200ResponseNotice
     */
    code: any | null;
    /**
     * The sender ID you asked for, which is awaiting approval.
     * @type {string}
     * @memberof SmsSend200ResponseNotice
     */
    requestedFrom: string;
    /**
     * 
     * @type {string}
     * @memberof SmsSend200ResponseNotice
     */
    message: string;
}

/**
 * Check if a given object implements the SmsSend200ResponseNotice interface.
 */
export function instanceOfSmsSend200ResponseNotice(value: object): value is SmsSend200ResponseNotice {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('requestedFrom' in value) || value['requestedFrom'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function SmsSend200ResponseNoticeFromJSON(json: any): SmsSend200ResponseNotice {
    return SmsSend200ResponseNoticeFromJSONTyped(json, false);
}

export function SmsSend200ResponseNoticeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SmsSend200ResponseNotice {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'requestedFrom': json['requestedFrom'],
        'message': json['message'],
    };
}

export function SmsSend200ResponseNoticeToJSON(json: any): SmsSend200ResponseNotice {
    return SmsSend200ResponseNoticeToJSONTyped(json, false);
}

export function SmsSend200ResponseNoticeToJSONTyped(value?: SmsSend200ResponseNotice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'requestedFrom': value['requestedFrom'],
        'message': value['message'],
    };
}

