/* tslint:disable */
/* eslint-disable */
/**
 * Moorsyl API
 * SMS, phone verification, and webhook APIs for Mauritania.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifySendRequest
 */
export interface VerifySendRequest {
    /**
     * 
     * @type {string}
     * @memberof VerifySendRequest
     */
    to: string;
}

/**
 * Check if a given object implements the VerifySendRequest interface.
 */
export function instanceOfVerifySendRequest(value: object): value is VerifySendRequest {
    if (!('to' in value) || value['to'] === undefined) return false;
    return true;
}

export function VerifySendRequestFromJSON(json: any): VerifySendRequest {
    return VerifySendRequestFromJSONTyped(json, false);
}

export function VerifySendRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifySendRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'],
    };
}

export function VerifySendRequestToJSON(json: any): VerifySendRequest {
    return VerifySendRequestToJSONTyped(json, false);
}

export function VerifySendRequestToJSONTyped(value?: VerifySendRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
    };
}

