/* tslint:disable */
/* eslint-disable */
/**
 * Moorsyl API
 * SMS, phone verification, and webhook APIs for Mauritania.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifySend200Response
 */
export interface VerifySend200Response {
    /**
     * 
     * @type {string}
     * @memberof VerifySend200Response
     */
    verificationId: string;
}

/**
 * Check if a given object implements the VerifySend200Response interface.
 */
export function instanceOfVerifySend200Response(value: object): value is VerifySend200Response {
    if (!('verificationId' in value) || value['verificationId'] === undefined) return false;
    return true;
}

export function VerifySend200ResponseFromJSON(json: any): VerifySend200Response {
    return VerifySend200ResponseFromJSONTyped(json, false);
}

export function VerifySend200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifySend200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'verificationId': json['verificationId'],
    };
}

export function VerifySend200ResponseToJSON(json: any): VerifySend200Response {
    return VerifySend200ResponseToJSONTyped(json, false);
}

export function VerifySend200ResponseToJSONTyped(value?: VerifySend200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verificationId': value['verificationId'],
    };
}

