/* tslint:disable */
/* eslint-disable */
/**
 * Moorsyl API
 * SMS, phone verification, and webhook APIs for Mauritania.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyCheckRequest
 */
export interface VerifyCheckRequest {
    /**
     * 
     * @type {string}
     * @memberof VerifyCheckRequest
     */
    verificationId: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyCheckRequest
     */
    code: string;
}

/**
 * Check if a given object implements the VerifyCheckRequest interface.
 */
export function instanceOfVerifyCheckRequest(value: object): value is VerifyCheckRequest {
    if (!('verificationId' in value) || value['verificationId'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function VerifyCheckRequestFromJSON(json: any): VerifyCheckRequest {
    return VerifyCheckRequestFromJSONTyped(json, false);
}

export function VerifyCheckRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyCheckRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'verificationId': json['verificationId'],
        'code': json['code'],
    };
}

export function VerifyCheckRequestToJSON(json: any): VerifyCheckRequest {
    return VerifyCheckRequestToJSONTyped(json, false);
}

export function VerifyCheckRequestToJSONTyped(value?: VerifyCheckRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verificationId': value['verificationId'],
        'code': value['code'],
    };
}

