/* tslint:disable */
/* eslint-disable */
/**
 * Moorsyl API
 * SMS, phone verification, and webhook APIs for Mauritania.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyCheck200Response
 */
export interface VerifyCheck200Response {
    /**
     * 
     * @type {string}
     * @memberof VerifyCheck200Response
     */
    status: VerifyCheck200ResponseStatusEnum;
}


/**
 * @export
 */
export const VerifyCheck200ResponseStatusEnum = {
    Approved: 'approved',
    Denied: 'denied'
} as const;
export type VerifyCheck200ResponseStatusEnum = typeof VerifyCheck200ResponseStatusEnum[keyof typeof VerifyCheck200ResponseStatusEnum];


/**
 * Check if a given object implements the VerifyCheck200Response interface.
 */
export function instanceOfVerifyCheck200Response(value: object): value is VerifyCheck200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function VerifyCheck200ResponseFromJSON(json: any): VerifyCheck200Response {
    return VerifyCheck200ResponseFromJSONTyped(json, false);
}

export function VerifyCheck200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyCheck200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function VerifyCheck200ResponseToJSON(json: any): VerifyCheck200Response {
    return VerifyCheck200ResponseToJSONTyped(json, false);
}

export function VerifyCheck200ResponseToJSONTyped(value?: VerifyCheck200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

