/* tslint:disable */
/* eslint-disable */
/**
 * Moorsyl API
 * SMS, phone verification, and webhook APIs for Mauritania.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyGet200Response
 */
export interface VerifyGet200Response {
    /**
     * 
     * @type {string}
     * @memberof VerifyGet200Response
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyGet200Response
     */
    to: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyGet200Response
     */
    status: VerifyGet200ResponseStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof VerifyGet200Response
     */
    attempts: number;
    /**
     * 
     * @type {Date}
     * @memberof VerifyGet200Response
     */
    expiresAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof VerifyGet200Response
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof VerifyGet200Response
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const VerifyGet200ResponseStatusEnum = {
    Pending: 'pending',
    Approved: 'approved',
    Expired: 'expired',
    Canceled: 'canceled'
} as const;
export type VerifyGet200ResponseStatusEnum = typeof VerifyGet200ResponseStatusEnum[keyof typeof VerifyGet200ResponseStatusEnum];


/**
 * Check if a given object implements the VerifyGet200Response interface.
 */
export function instanceOfVerifyGet200Response(value: object): value is VerifyGet200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('attempts' in value) || value['attempts'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function VerifyGet200ResponseFromJSON(json: any): VerifyGet200Response {
    return VerifyGet200ResponseFromJSONTyped(json, false);
}

export function VerifyGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'to': json['to'],
        'status': json['status'],
        'attempts': json['attempts'],
        'expiresAt': (new Date(json['expiresAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function VerifyGet200ResponseToJSON(json: any): VerifyGet200Response {
    return VerifyGet200ResponseToJSONTyped(json, false);
}

export function VerifyGet200ResponseToJSONTyped(value?: VerifyGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'to': value['to'],
        'status': value['status'],
        'attempts': value['attempts'],
        'expiresAt': ((value['expiresAt']).toISOString()),
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

